using Microsoft.Data.SqlClient;
using System.Data;

namespace _45Disconnected
{
    internal class Program
    {
        static void Main(string[] args)
        {
            string Connection = "Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=IET;Integrated Security=True";
            #region SelectQuery
                
            //SqlConnection connection = new SqlConnection(Connection);
            //SqlDataAdapter da = new SqlDataAdapter("Select * from Employee", connection);
            //da.MissingSchemaAction=MissingSchemaAction.AddWithKey;

            //DataSet ds = new DataSet();
            //da.Fill(ds,"Employee");


            //foreach (DataRow row in ds.Tables["Employee"].Rows)
            //{
            //    int id = Convert.ToInt32(row["Id"]);
            //    string nm = row["Name"].ToString();
            //    string add = row["Address"].ToString();
            //    Console.WriteLine($"Id: {id}, Name: {nm}, Address: {add}");
            //}


            #endregion


            #region INSERT Query
            SqlConnection con = new SqlConnection(Connection);
            SqlDataAdapter da = new SqlDataAdapter("SELECT * FROM EMPLOYEE", con);

            da.MissingSchemaAction = MissingSchemaAction.AddWithKey;

            SqlCommandBuilder builder = new SqlCommandBuilder(da);

            DataSet ds = new DataSet();
            da.Fill(ds, "Employee");
            //ds.GetXml()

            Console.WriteLine("Enter ID");
            int id=Convert.ToInt32(Console.ReadLine());

            Console.WriteLine("Enter Name:");
            string nm = Console.ReadLine();
            Console.WriteLine("Enter Address:");
            string add = Console.ReadLine();

            DataRow newRow = ds.Tables["Employee"].NewRow();
            newRow["id"] = id;
            newRow["Name"] = nm;
            newRow["Address"] = add;

            ds.Tables["Employee"].Rows.Add(newRow);

            da.Update(ds, "Employee");//Insert Query is generated by CommandBuilder
            Console.WriteLine("Record inserted!");


            #endregion


        }
    }
}
