using System;



namespace _36CSharpFeatures
{
    internal class Program
    {
        static void Main(string[] args)
        {
            #region Partial Class

            //CMath cMath = new CMath();
            //Console.WriteLine($"Add result ={cMath.Add(20,10)}");
            //Console.WriteLine($"Multiply result={cMath.Multiply(10,10)}");
            #endregion

           
           #region Nullable types [? = nullable operator]

            string name = null ; //allowed already
           
            //int c=null  not allowed

            // int dept = null; error because value type cant store null
            //hence use nullable operator

            int? dept = null;
            int? deptid=null;

            if (deptid.HasValue)
            {
                Console.WriteLine(deptid.Value);
            }
            else
            {
                Console.WriteLine("deptid=null");
            }

            DateTime? dt = null;

            //another way
            Nullable<int> n = null;
            Nullable<DateTime> d = null;

            #endregion

            #region ObjectInitializer {}

            //initializes object without constructor declaration 
            //constructor is created by compiler
            

            Food food=new Food() { id=101,name="pizza"};
            Console.WriteLine(food.id+"  "+food.name);

            Food food1 = new Food() { id = 201, name = "burer", price = 200 };
            Console.WriteLine(food1.id+" "+food1.name+" "+food1.price);

            #endregion

            #region collection initialiser{}

            //collection initializer 
            // int array is initialized at the time of declaration

            int[] arr1 = new int[] { 10, 20, 30, 40, 50 };
            foreach (int ele in arr1)
            {
                Console.WriteLine(ele);
            }


            //string array initialization

            string[] arr = new string[] { "bob", "alice", "alexa", "nick" };

            foreach (string ele in arr)
            {
                Console.WriteLine(ele);
            }



            //collection initializer combined with object initializer

            List<Food> foods = new List<Food>() {
               new Food(){id=11,name="pasta",price=150},
               new Food(){id=22,name="burger",price=80},
               new Food(){id=33,name="maggi",price=50}
            };

            foreach(Food f in foods)
            {
                Console.WriteLine($"FoodId:{f.id} , Food Name={f.name}  ,Food Price={f.price}");
            }
            #endregion

            #region Autogenerated Properties

            Account ac1 = new Account(){
                AcNumber = 123456890,
                AccountHolder = "abc",
                AccountType="savings",
                balance=30000.00,
                transactionsInAWeek=new List<int>() { 2,3,1,0,1,0,0},
                cardtype="debit card"
            };

            Console.WriteLine($"AcNumber:{ac1.AcNumber} , AcHolder:{ac1.AccountHolder} , AcType:{ ac1.AccountType}, Balance:{ac1.balance},CARdType:{ac1.cardtype}");
           



            Account ac2 = new Account()
            {
                AcNumber = 1122334455,
                AccountHolder = "xyz",
                AccountType = "shopping",
                balance = 500000.00,
                transactionsInAWeek = new List<int>() { 5, 3, 1, 0, 1, 0, 4 },
                cardtype = "credit card"
            };

            Console.WriteLine($"AcNumber:{ac2.AcNumber} , AcHolder:{ac2.AccountHolder} , AcType:{ac2.AccountType}, Balance:{ac2.balance},CARdType:{ac2.cardtype}");



            #endregion

            #region Implicit Type

            //Test test = new Test();
            //Food food2 = test.GetSomething(2) as Food;


            //int value= Convert.ToInt32( test.GetSomething(1) );

            //Object num= test.GetSomething(null) ;


            //var i=100;
            //var str = "HElloe";

            //var Food = new Food();



            //Test obj= new Test();
            //Console.WriteLine("Enter your choice");
            //int ch = Convert.ToInt32(Console.ReadLine());

            //var result=obj.GetSomething(ch);


            //Console.WriteLine(result);



            //// Implicit type has rules:
            //// var is always local scoped
            //// var can not be used as a pramameter type of a method
            //// var can be used when the type is known at compile time.
            //// var gets defination at compile time
            //// var can not be used for fields, properties or method
            ///parameters or method return types.

            #endregion

            #region Annonymous type:A class Without name


            //anonymous type class
            //of movie

            Console.WriteLine();
            var v1 = new { movieid = 11, Moviename = "Dhurander", actor = "Ranbir", actress = "clinic+wli" };
            Console.WriteLine(v1.GetType().ToString());
            Console.WriteLine($"{v1.movieid},{v1.Moviename},{v1.actor},{v1.actress}");

            var v2 = new { id = 55, type = "junkfood", foodname = "samosa" };
            Console.WriteLine(v2.GetType().ToString());
            Console.WriteLine($"{v2.id} , {v2.type} , {v2.foodname}");



            List<Holder> dbholder = new List<Holder>()
            {
                new Holder(){id=1,name=null,designation="abc"}
            };

            foreach(Holder holder in dbholder)
            {
                Console.WriteLine(holder.id);
                Console.WriteLine(holder.name);
                Console.WriteLine(holder.designation);
            }
            #endregion




        }

        //used for objectinitializer and collection initializer
        public class Food
          
        {
            public int id;
            public string name;
            public int price;
        }

        //used for autogenerated properties


        public class Holder
        {
            public int? id { get; set; }
            public string? name { get; set; }

            public string? designation { get; set; }
        }
       public class Account
        {
            public int AcNumber { get; set; }
            public string AccountHolder { get; set; }

            public string AccountType { get; set; }

            public double balance{ get; set; }

            public List<int> transactionsInAWeek { get; set; }

            public string cardtype { get; set; }
        }






        public class Test
        {

            public object GetSomething(Nullable<int> choice)
            {
                if (choice == 1)
                {
                    return 100;
                }
                else if (choice == 2)
                {

                    return new Food() { id = 1, name = "pitzza", price = 500 };
                }

                else
                {
                    return null;
                }
            }
        }


        public class Movie
        {
            public int movieId { get; set; }
            public string Moviename { get; set; }
            public string actor { get; set; }

            public string actress { get; set; }
        }

        public class Food2

        {
            public int id { get; set; }
            public string type { get; set; }
            public string foodname { get; set; }
        }
    }
}
